pipeline{
 agent any
 environment {
   ANYPOINT = credentials('deploy-anypoint-user')
  }
 stages {
 		stage ('Build'){
 		steps {
 			withMaven(maven:'maven'){
 				sh 'mvn -f mule-jenkins-pipeline/pom.xml clean install'
 			}
 		}
 	}
 	
 }

}
