pipeline{
 agent any
 environment {
   ANYPOINT = credentials('deploy-anypoint-user')
  }
 stages {
 	stage ('Build'){
 		steps {
 			withMaven(maven:'maven'){
 				sh 'mvn -f samplemunit/pom.xml clean install'
 			}
 		}
 	}
 	stage ('Deploy'){
 		steps {
 			withMaven(maven:'maven'){
 				sh 'mvn -f samplemunit/pom.xml package deploy  -Dusername=$ANYPOINT_USR -Dpassword=$ANYPOINT_PSW -Denvironment=Sandbox -DmuleDeploy'
 			}
 		}
 	}
 }

tools {
    maven '3.3.5'
  }
}
